## 자바 JDK로 프로그래밍 날개 달기

### 14. 예외 처리

1. 예외 클래스
    - 오류란 무엇인가요?

         - 프로그램에서 오류가 발생하는 상황

        프로그램 코드 작성 중 실수로 발생하는 컴파일 오류(compile error)

        → 개발 환경에서 대부분 원인을 알 수 있음, 컴파일 오류를 모두 수정해야 프로그램이 정상적으로 실행되므로, 문법적으로 오류가 있다는 것을 바로 알 수 있음

        실행 중인 프로그램이 의도하지 않은 동작을 하거나 프로그램이 중지되는 실행 오류(runtime error)

        → 프로그램 실행 중에 발생하는 오류는 예측하기 어려운 경우가 많음, 프로그램이 비정상 종료되면서 갑자기 멈춰버림

         - 버그 : 실행 오류 중 프로그램을 잘못 구현하여 의도한 바와 다르게 실행되어 생기는 오류

         - 로그 : 소프트웨어 실행 중에 발생하는 여러 상황을 기록한 내용으로서 주로 파일에 기록(로그 파일)

         - 예외 처리 목적 : 프로그램이 비정상 종료되는 것을 방지하기 위한 것

         - 예외가 발생했을 때 로그를 남겨두면 예외 상황을 파악하고 버그를 수정하는 데 도움을 받을 수 있음

    - 오류와 예외 → 실행 오류

         - 오류 클래스는 모두 Throwable 클래스에 상속받음

         - error : 자바 가상 머신에서 발생하는 시스템 오류

        → 사용 가능한 동적 메모리가 없는 경우, 스택 메모리의 오버플로가 발생한 경우

        프로그램에서 제어할 수 없음

        Error 클래스의 하위 클래스는 시스템에서 발생하는 오류를 다루며 프로그램에서 제어하지 않음

         - exception : 예외

        → 프로그램에서 파일을 읽어 사용하려는데 파일이 없는 경우, 네트워크로 데이터를 전송하려는데 연결이 안된 경우, 배열 값을 출력하려는데 배열 요소가 없는 경우

        프로그램에서 제어할 수 있음

        Exception 클래스와 그 하위에 있는 예외 클래스는 프로그램에서 제어 가능

    - 예외 클래스(Exception Class)의 종류

         - IOException 클래스 : 입출력에 대한 예외를 처리

         - RuntimeException 클래스 : 실행 중 발생할 수 있는 오류에 대한 예외 처리

2. 예외 처리하기
    - try-catch문

        ```java
        try{
        	예외가 발생할 수 있는 코드 부분
        }catch(처리할 예외 타입 e){
        	try 블록 안에서 예외가 발생했을 때 예외를 처리하는 부분
        }
        ```

         - try-catch 문 사용하기

         > try-catch문 사용하기

        ```java
        package exception;

        public class ArrayExceptionHandling {
        	public static void main(String[] args) {
        		int[] arr = new int[5];

        		// 예외가 발생할 수 있으므로 try 블록에 작성
        		try {
        			// 배열에 저장하려는 값의 개수가 배열 범위를 벗어났기 때문에 예외 발생
        			for (int i = 0; i <= 5; i++) {
        				arr[i] = i;
        				System.out.println(arr[i]);
        			}
        		} catch (Exception e) {
        			// 예외가 발생하면 catch 블록 수행
        			System.out.println(e);
        			System.out.println("예외 처리 부분");
        		}
        		System.out.println("프로그램 종료");
        	}
        }
        ```

    - 컴파일러에 의해 예외가 체크되는 경우

         - 자바에서 제공하는 많은 예외 클래스들은 컴파일러에 의해 처리됨

        → 자바에서 예외처리를 하지 않으면 컴파일 오류가 계속 남음

         - 파일 입출력에서 발생하는 예외 처리하기

         > try-catch문 사용하기

        ```java
        package exception;

        import java.io.FileInputStream;
        import java.io.FileNotFoundException;

        public class ExceptionHandling1 {
        	public static void main(String[] args) {
        		try {
        			FileInputStream fis = new FileInputStream("a.txt");
        		} catch (FileNotFoundException e) {
        			System.out.println(e); // 예외 클래스의 toString() 메서드 호출
        		}
        		System.out.println("여기도 수행됩니다."); // 정상 출력
        	}
        }
        /*
         * java.io.FileNotFoundException: a.txt (No such file or directory) 여기도 수행됩니다.
         */
        ```

        → 예외 처리를 한다고 해서 프로그램의 예외 상황 자체를 막을 수는 없지만,  예외처리를 하면 예외 상황을 알려주는 메시지를 볼 수 있고, 프로그램이 비정상 종료되지 않고 계속 수행되도록 만들 수 있음

    - try-catch-finally 문

         - 프로그램에서 사용한 리소스는 프로그램이 종료되면 자동으로 해제됨

        → 사용한 시스템 리소스는 사용 후 반드시 close()메서드로 닫아주어야 함

         - 비정상적으로 종료된 경우에도 리소스를 닫아야 하기 때문에 try 블록 뿐 아니라 catch 블록에도 close() 메서드를 사용해야 함

         - finally 사용 형식

        ```java
        try{
        	예외가 발생할 수 있는 부분
        }catch(처리할 예외 타입 e){
        	예외를 처리하는 부분
        }finally{
        	항상 수행되는 부분
        }
        ```

        → try 블록이 수행되면 finally 블록은 어떤 경우에도 반드시 수행됨

         - try-catch-catch... 각 블록마다 리소스를 해제하지 않고 finally 블록에서 한번만 해제해 주면 됨

         > finally 블록 사용하기

        ```java
        package exception;

        import java.io.FileInputStream;
        import java.io.FileNotFoundException;
        import java.io.IOException;

        public class ExceptionHanlding3 {
        	public static void main(String[] args) {
        		FileInputStream fis = null;

        		try {
        			fis = new FileInputStream("a.txt");
        			//FileNotFoundException 예외 처리
        		} catch (FileNotFoundException e) {
        			System.out.println(e);
        			return; // 테스트를 위해 강제로 return 하기
        		} finally {// return 문과 상관없이 finally 블록 수행
        			if (fis != null) {
        				try {
        					fis.close(); // 파일 입력 스트림 닫기
        				} catch (IOException e) {
        					e.printStackTrace();
        				}
        			}
        			System.out.println("항상 수행됩니다.");
        		}
        		System.out.println("여기도 수행됩니다.");
        	}
        }
        ```

    - try-with-resources문

         - try-with-resources문을 제공하여 close()메소드를 명시적으로 호출하지 않아도 try블록 내에서 열린 리소스를 자동으로 닫도록 만들 수 있음

         - try-with-resources 문법을 사용하려면 해당 리소스가 AutoCloseable 인터페이스를 구현해야 함

         - AutoCloseable 인터페이스에는 close() 메서드가 잇고 이를 구현한 클래스는 close()를 명시적으로 호출하지 않아도 close() 메서드 부분이 호출됨

         - AutoCloseable 인터페이스

         > AutoCloseable 인터페이스 구현하기

        ```java
        package exception;

        public class AutoCloseObj implements AutoCloseable {
          @Override
          public void close() throws Exception {
            System.out.println("리소스가 close() 되었습니다.");
          }
        }
        ```

         > try-with-resources문 사용하기(1)

         - close() 메서드가 제대로 호출되는지 확인

        ```java
        package exception;

        public class AutoCloseTest {
        	public static void main(String[] args) {
        		try (AutoCloseObj obj = new AutoCloseObj()) {// 사용할 리소스 선언

        		} catch (Exception e) {
        			System.out.println("예외부분입니다.");
        		}
        	}
        }
        //리소스가 close() 되었습니다.
        ```

         > try-with-resources문 사용하기(2)

         - 예외가 발생하여 종료되는 경우에도 close() 메서드가 잘 호출되는지 확인

        ```java
        package exception;

        public class AutoCloseObjTest {

        	public static void main(String[] args) {
        		try (AutoCloseObj obj = new AutoCloseObj()) {
        			throw new Exception(); // 강제 예외 발생 
        		} catch (Exception e) {
        			System.out.println("예외부분입니다.");
        		}
        	}
        }
        //리소스가 close() 되었습니다.
        //예외 부분입니다.
        ```

         - 향상된 try-with-resources 문(자바 9에서 추가된 문법)

        ```java
        AutoCloseObj obj = new AutoCloseObj();
        try(obj){ // 외부에서 선언한 변수를 그대로 쓸 수 있음
        	throw new Exception();
        }catch(Exception e){
        	System.out.println("예외 부분입니다.")
        }

        /*
        AutoCloseObj obj = new AutoCloseObj();
        try(AutoCloseObj obj2 =obj){ // 다른 참조 변수로 다시 선언해야 함
        	throw new Exception();
        }catch(Exception e){
        	System.out.println("예외 부분입니다.")
        }
        */
        ```

3. 예외 처리 미루기
    - 예외 처리를 미루는 throws 사용하기

         - 예외를 해당 메서드에서 처리하지 않고 미룬 후 메서드를 호출하여 사용하는 부분에서 예외를 처리하는 방법

         > throws로 예외 미루기

        ```java
        package exception;

        import java.io.FileInputStream;
        import java.io.FileNotFoundException;

        public class ThrowsException {
        	public Class loadClass(String fileName, String className) throws FileNotFoundException, ClassNotFoundException {
        		// 두 예외를 메서드가 호출될 때 처리하도록 미룸
        		FileInputStream fis = new FileInputStream(fileName); // FileNotFoundException발생 가능
        		Class c = Class.forName(className); // ClassNotFoundException 발생 가능
        		return c;
        	}

        	public static void main(String[] args) {
        		ThrowsException test = new ThrowsException();
        		test.loadClass("a.txt", "java.lang.String"); // 메서드를 호출할 때 예외를 처리함
        	}
        }
        ```

         - throws를 활용하여 예외 처리 미루기

        → 위 코드에서  `test.loadClass("a.txt", "java.lang.String");` 부분에 오류 발생

        해결 옵션  

        ① Add throws declation 

        : main()함수 선언 부분에 throws FileNotFoundException, ClassNotFoundException을 추가하고 예외처리를 미룬다는 뜻

         - 예외를 처리하는 것이 아니라 대부분의 프로그램이 비정상 종료됨

        ② surround with try/multi-catch

        ```java
        public static void main(String[] args) {
        		ThrowsException test = new ThrowsException();
        		try{		
        			test.loadClass("a.txt", "java.lang.String"); // 메서드를 호출할 때 예외를 처리함
        		}catch(FileNotFoundException|ClassNotFoundException e){
        			e.printStackTrace();
        		}
        }
        ```

        → 여러 예외를 한 문장으로 처리하는 try-catch 구문이 생성됨

        ③ surround with try

        ```java
        public static void main(String[] args) {
        		ThrowsException test = new ThrowsException();
        		try{		
        			test.loadClass("a.txt", "java.lang.String"); // 메서드를 호출할 때 예외를 처리함
        		}catch(FileNotFoundException e){
        			e.printStackTrace();
        		}catch(ClassNotFoundException e){
        			e.printStackTrace();
        		}
        }
        ```

        → 각 상황마다 다른 방식으로 예외처리를 함

    - 다중 예외 처리

         - 반드시 예외 처리를 해야하는 경우 이외에도 예외처리를 해야할 때가 있음

        (배열을 사용할 때 배열의 크기보다 큰 위치, 즉 요소가 존재하지 않는 위치로 접근하는 경우 → 컴파일러에 의해 체크되지 않음)

         - 어떤 예외가 발생할지 미리 알 수 없지만 모든 예외상황을 처리하고자 한다면 맨 마지막 부분에 Exception 클래스를 활용하여 catch 블록을 추가

         > 여러 catch문 사용하기

        ```java
        package exception;

        import java.io.FileInputStream;
        import java.io.FileNotFoundException;

        public class ThrowsException {
        	public Class loadClass(String fileName, String className) throws FileNotFoundException, ClassNotFoundException {
        		// 두 예외를 메서드가 호출될 때 처리하도록 미룸
        		FileInputStream fis = new FileInputStream(fileName); // FileNotFoundException발생 가능
        		Class c = Class.forName(className); // ClassNotFoundException 발생 가능
        		return c;
        	}

        	public static void main(String[] args) {
        		ThrowsException test = new ThrowsException();
        		try {
        			test.loadClass("a.txt", "java.lang.String");
        		} catch (FileNotFoundException e) {
        			// TODO Auto-generated catch block
        			e.printStackTrace();
        		} catch (ClassNotFoundException e) {
        			// TODO Auto-generated catch block
        			e.printStackTrace();
        		} catch(Exception e) { // Exception 클래스로 그 외 예외상황 처리 
        			e.printStackTrace(); 
        		}
        	}
        }
        ```

         - 다중 예외 처리에서 주의사항

        예외는 catch문을 선언한 순서대로 검사 → 맨 위에 catch(Exception e)문장을 쓰면 발생하는 모든 예외 클래스는 Exception 상위 클래스로 자동 형 변환되어 오류가 발생

        ⇒ 기본 예외 처리를 하는 Exception 클래스 블록은 여러 예외 처리 블록의 가장 아래에 놓여야 함

4. 사용자 정의 예외
    - 사용자 정의 예외 클래스 구현하기

        → 기존 JDK에서 제공하는 예외 클래스 중 가장 유사한 클래스를 상속받는 것이 좋음

        (유사한 예외 클래스를 잘 모르겠다면 가장 상위 클래스인 Exception 클래스에서 상속)

         > 사용자 정의 예외 구현하기

        ```java
        package exception;

        public class IDFormatException extends Exception {
          // 생성자
          public IDFormatException(String message) { // 생성자의 매개변수로 예외 상황 메시지를 받음
            super(message);
          }
        }
        ```

         > 사용자 정의 예외 테스트 하기

        ```java
        package exception;

        public class IDFormatTest {
        	// 변수 선언
        	private String userID;

        	// 생성자
        	public String getUserID() {
        		return userID;
        	}

        	// ==아이디에 대한 제약 조건 구현==
        	// IDFormatException 예외를 setUserID() 메서드가 호출될때 처리하도록 미룸
        	public void setUserID(String userID) throws IDFormatException {
        		// 강제로 예외 발생시킴
        		if (userID == null) {
        			throw new IDFormatException("아이디는 null일 수 없습니다.");
        		} else if (userID.length() < 8 || userID.length() > 20) {
        			throw new IDFormatException("아이디는 8자 이상 20자 이하로 쓰세요");
        		}
        		this.userID = userID;
        	}

        	public static void main(String[] args) {
        		IDFormatTest test = new IDFormatTest();
        		// 아이디 값이 null인 경우
        		String userID = null;
        		try {
        			test.setUserID(userID);
        		} catch (IDFormatException e) {
        			System.out.println(e.getMessage());
        		}
        		// 아이디 값이 8자 이하인 경우
        		userID = "1234567";
        		try {
        			test.setUserID(userID);
        		} catch (IDFormatException e) {
        			System.out.println(e.getMessage());
        		}
        	}
        }
        ```

    - 예외 처리를 할 때는 로그를 잘 남길 것!

         - 오류가 발생했을 때 로그를 보고 오류가 발생하는 코드를 순서대로 따라가며 확인할 수 있고 원인을 찾을 수 있음

         - 로그는 정보의 의미에 따라 레벨을 나누어 관리(간단한 정보의미를 가진 로구~ 심각한 예외가 발생했을 때의 로그)

        → 로그를 체계적이고 의미있게 남겨서 시스템에 오류가 났을때 그 원인을 유추해볼 수 있어야 함

5. 연습문제
    - 모든 예외 클래스의 최상위 클래스는 [Exception 클래스]입니다.
    - try{} 블록이 수행되면 항상 수행되는 블록으로서 주로 열린 파일이나 네트워크 리소스의 해제를 수행하는 블록을 구현하는 예약어는 [finally]입니다.
    - 예외 처리를 위해 try-catch 문장을 사용할 수도 있지만, 예외를 직접 처리하지 않고 미룰 때 사용하는 예약어는 [**throws**]입니다.
    - 사용자가 예외를 직접 발생시키기 위해 사용하는 예약어는 [**throw**]입니다.
